package com.deotis.uixmlpaser.visitor;

import com.deotis.uixmlpaser.element.AsyncXMLElement;
import com.deotis.uixmlpaser.element.BargeinDTMFXMLElement;
import com.deotis.uixmlpaser.element.BargeinSwitchXMLElement;
import com.deotis.uixmlpaser.element.ClearDTMFXMLElement;
import com.deotis.uixmlpaser.element.CommonXMLElement;
import com.deotis.uixmlpaser.element.ComponentsXMLElement;
import com.deotis.uixmlpaser.element.ErrCountAddVxmlXMLElement;
import com.deotis.uixmlpaser.element.ErrCountOverCountXMLElement;
import com.deotis.uixmlpaser.element.ErrCountOverXMLElement;
import com.deotis.uixmlpaser.element.ErrDigitAddVxmlXMLElement;
import com.deotis.uixmlpaser.element.ErrDigitVoiceCountXMLElement;
import com.deotis.uixmlpaser.element.ErrDigitVoiceXMLElement;
import com.deotis.uixmlpaser.element.ErrDigitXMLElement;
import com.deotis.uixmlpaser.element.ErrInputAddVxmlXMLElement;
import com.deotis.uixmlpaser.element.ErrInputCountXMLElement;
import com.deotis.uixmlpaser.element.ErrInputXMLElement;
import com.deotis.uixmlpaser.element.ErrLastBargeinXMLElement;
import com.deotis.uixmlpaser.element.ErrLinkScenarioXMLElement;
import com.deotis.uixmlpaser.element.ErrMaxCountXMLElement;
import com.deotis.uixmlpaser.element.ErrMaxTimeXMLElement;
import com.deotis.uixmlpaser.element.ErrProcessXMLElement;
import com.deotis.uixmlpaser.element.ErrTimeAddVxmlXMLElement;
import com.deotis.uixmlpaser.element.ErrTimeOverCountXMLElement;
import com.deotis.uixmlpaser.element.ErrTimeOverXMLElement;
import com.deotis.uixmlpaser.element.ErrXMLElement;
import com.deotis.uixmlpaser.element.ItemANIXMLElement;
import com.deotis.uixmlpaser.element.ItemAddUserVxmlXMLElement;
import com.deotis.uixmlpaser.element.ItemAssignServiceCodeXMLElement;
import com.deotis.uixmlpaser.element.ItemCTILinkXMLElement;
import com.deotis.uixmlpaser.element.ItemDNXMLElement;
import com.deotis.uixmlpaser.element.ItemDigitAtServiceXMLElement;
import com.deotis.uixmlpaser.element.ItemLocationMemoryXMLElement;
import com.deotis.uixmlpaser.element.ItemPopupInfoToAgentXMLElement;
import com.deotis.uixmlpaser.element.ItemPreviousMemoryXMLElement;
import com.deotis.uixmlpaser.element.ItemPushMemoryIdxXMLElement;
import com.deotis.uixmlpaser.element.ItemQueueNumToAgentXMLElement;
import com.deotis.uixmlpaser.element.ItemReasonAtServiceXMLElement;
import com.deotis.uixmlpaser.element.ItemkeyXMLElement;
import com.deotis.uixmlpaser.element.ItemkindXMLElement;
import com.deotis.uixmlpaser.element.ItemnameXMLElement;
import com.deotis.uixmlpaser.element.ItemservicecodeXMLElement;
import com.deotis.uixmlpaser.element.ItemservicenameXMLElement;
import com.deotis.uixmlpaser.element.ItemtextXMLElement;
import com.deotis.uixmlpaser.element.LinkXMLElement;
import com.deotis.uixmlpaser.element.PlayVoice4XMLElement;
import com.deotis.uixmlpaser.element.PlayVoiceXMLElement;
import com.deotis.uixmlpaser.element.PointXMLElement;
import com.deotis.uixmlpaser.element.ScenarioXMLElement;
import com.deotis.uixmlpaser.element.SelectVoiceCountXMLElement;
import com.deotis.uixmlpaser.element.SelectVoiceXMLElement;
import com.deotis.uixmlpaser.element.Start4XMLElement;
import com.deotis.uixmlpaser.element.TableXMLElement;
import com.deotis.uixmlpaser.element.TablesXMLElement;
import com.deotis.uixmlpaser.element.UnkownedXMLElement;

public interface UIXMLVisitor {
	
	public void visit(ScenarioXMLElement element);
	public void visit(TablesXMLElement element);
	public void visit(TableXMLElement element);
	public void visit(LinkXMLElement element);
	public void visit(PointXMLElement element);
	
	public void visit(ComponentsXMLElement element);
	public void visit(Start4XMLElement element);
	public void visit(PlayVoice4XMLElement element);
	
	public void visit(CommonXMLElement element);
	public void visit(ItemkeyXMLElement element);
	public void visit(ItemkindXMLElement element);
	public void visit(ItemnameXMLElement element);
	public void visit(ItemservicecodeXMLElement element);
	public void visit(ItemservicenameXMLElement element);
	public void visit(ItemtextXMLElement element);
	public void visit(ItemLocationMemoryXMLElement element);
	public void visit(ItemPreviousMemoryXMLElement element);
	public void visit(ItemPushMemoryIdxXMLElement element);
	public void visit(ItemAssignServiceCodeXMLElement element);
	public void visit(ItemAddUserVxmlXMLElement element);
	public void visit(ItemCTILinkXMLElement element);
	public void visit(ItemDigitAtServiceXMLElement element);
	public void visit(ItemReasonAtServiceXMLElement element);
	public void visit(ItemQueueNumToAgentXMLElement element);
	public void visit(ItemPopupInfoToAgentXMLElement element);
	public void visit(ItemDNXMLElement element);
	public void visit(ItemANIXMLElement element);
	
	public void visit(PlayVoiceXMLElement element);
	public void visit(AsyncXMLElement element);
	public void visit(BargeinDTMFXMLElement element);
	public void visit(ClearDTMFXMLElement element);
	public void visit(BargeinSwitchXMLElement element);
	public void visit(SelectVoiceXMLElement element);
	public void visit(SelectVoiceCountXMLElement element);
	
	public void visit(ErrXMLElement element);
	public void visit(ErrMaxTimeXMLElement element);
	public void visit(ErrMaxCountXMLElement element);
	public void visit(ErrInputXMLElement element);
	public void visit(ErrInputCountXMLElement element);
	public void visit(ErrCountOverXMLElement element);
	public void visit(ErrCountOverCountXMLElement element);
	public void visit(ErrTimeOverXMLElement element);
	public void visit(ErrTimeOverCountXMLElement element);
	public void visit(ErrLastBargeinXMLElement element);
	public void visit(ErrProcessXMLElement element);
	public void visit(ErrLinkScenarioXMLElement element);
	public void visit(ErrDigitXMLElement element);
	public void visit(ErrDigitVoiceXMLElement element);
	public void visit(ErrDigitVoiceCountXMLElement element);
	public void visit(ErrInputAddVxmlXMLElement element);
	public void visit(ErrTimeAddVxmlXMLElement element);
	public void visit(ErrCountAddVxmlXMLElement element);
	public void visit(ErrDigitAddVxmlXMLElement element);
	
	public void visit(UnkownedXMLElement element);
}
